# -*- coding: utf-8 -*-
"""Formatted Excel output writer for the Levisol planning engine."""
import numpy as np
import pandas as pd


def write_output(path, data, norms, hub_norms, plan, params=None):
    """Write the full plan + norms + cost summary + exceptions workbook."""
    sku = data["sku"]
    line = sku["Line"]
    pen = sku["Penalty cost (per kL)"]
    contr = sku["Contractual"]
    tc_ph, tc_hc = data["tc_ph"], data["tc_hc"]
    pc = data["prod_cost"]
    c = plan["costs"]
    params = params or {}

    with pd.ExcelWriter(path, engine="xlsxwriter") as xw:
        wb = xw.book
        h1 = wb.add_format({"bold": True, "font_size": 14})
        wrap = wb.add_format({"text_wrap": True, "valign": "top"})
        money = wb.add_format({"num_format": "#,##0"})

        # ---- 0. README ------------------------------------------------------
        ws = wb.add_worksheet("READ ME")
        xw.sheets["READ ME"] = ws
        lines = [
            "LEVISOL MONTHLY PRODUCTION & DISTRIBUTION PLAN - OUTPUT WORKBOOK",
            "",
            "Sheets:",
            "  1. Cost Summary        - total plan cost broken into components",
            "  2. Production Plan     - kL per SKU per plant (25 kL batches)",
            "  3. Plant-Hub Flows     - primary transport legs",
            "  4. Hub-CFA Dispatch    - secondary transport legs",
            "  5. Hub Stock Position  - closing stock vs safety-stock target",
            "  6. Norms - CFA         - safety stock / reorder point / days of cover",
            "  7. Norms - Hub         - hub-level norms at 98% service level",
            "  8. Exceptions          - unmet demand, buffer shortfalls, data flags",
            "",
            "All quantities in kL, all costs in INR.",
            "Generated by the Levisol Planning Tool.",
        ]
        for i, t in enumerate(lines):
            ws.write(i, 0, t, h1 if i == 0 else None)
        ws.set_column(0, 0, 110)

        # ---- 1. Cost summary --------------------------------------------------
        tot_cash = (c["production"] + c["transport_plant_hub"] +
                    c["transport_hub_cfa"] + c["penalty_unmet"])
        cost_rows = [
            ("Production cost", c["production"]),
            ("Transport: plant → hub", c["transport_plant_hub"]),
            ("Transport: hub → CFA", c["transport_hub_cfa"]),
            ("Penalty: unmet January demand", c["penalty_unmet"]),
            ("TOTAL CASH COST OF PLAN", tot_cash),
            ("Memo: hub safety-stock shortfall, risk-weighted*", c["buffer_risk_hub"]),
            ("Memo: CFA safety-stock top-up shortfall, risk-weighted*", c["buffer_risk_cfa"]),
        ]
        cs = pd.DataFrame(cost_rows, columns=["Cost element", "INR"])
        cs.to_excel(xw, sheet_name="Cost Summary", index=False, startrow=1)
        ws = xw.sheets["Cost Summary"]
        ws.write(0, 0, "COST SUMMARY - JANUARY 2026 PLAN", h1)
        ws.write(len(cost_rows) + 3, 0,
                 "*Not a cash cost: prioritisation weight applied to safety-stock "
                 "shortfalls (buffer_weight × SKU penalty). Reported for transparency.",
                 wrap)
        for k, v in params.items():
            pass
        ws.set_column(0, 0, 45); ws.set_column(1, 1, 20, money)

        # ---- 2. Production plan ----------------------------------------------
        rows = [(s, p, q, line[s], q / 25.0, float(pc[p]), q * float(pc[p]))
                for (s, p), q in sorted(plan["prod"].items())]
        pr = pd.DataFrame(rows, columns=["SKU", "Plant", "Production (kL)",
                                         "Line", "Batches (25 kL)",
                                         "Cost/kL (INR)", "Production cost (INR)"])
        pr.to_excel(xw, sheet_name="Production Plan", index=False)
        xw.sheets["Production Plan"].set_column(0, 6, 16)

        # ---- 3. Plant->Hub flows ----------------------------------------------
        rows = [(s, p, h, q, tc_ph[(p, h)], q * tc_ph[(p, h)])
                for (s, p, h), q in sorted(plan["flow_ph"].items())]
        f1 = pd.DataFrame(rows, columns=["SKU", "Plant", "Hub", "Volume (kL)",
                                         "Rate (INR/kL)", "Cost (INR)"])
        f1.to_excel(xw, sheet_name="Plant-Hub Flows", index=False)
        xw.sheets["Plant-Hub Flows"].set_column(0, 5, 15)

        # ---- 4. Hub->CFA dispatch ----------------------------------------------
        rows = [(s, h, cfa, q, tc_hc[(h, cfa)], q * tc_hc[(h, cfa)])
                for (s, cfa, h), q in sorted(plan["flow_hc"].items())]
        f2 = pd.DataFrame(rows, columns=["SKU", "From Hub", "To CFA", "Volume (kL)",
                                         "Rate (INR/kL)", "Cost (INR)"])
        f2.to_excel(xw, sheet_name="Hub-CFA Dispatch", index=False)
        xw.sheets["Hub-CFA Dispatch"].set_column(0, 5, 15)

        # ---- 5. Hub stock position ----------------------------------------------
        sshub = hub_norms.set_index(["Product Name", "Hub"])["safety_stock_kl"]
        rows = [(s, h, v, float(sshub.get((s, h), 0.0)),
                 v - float(sshub.get((s, h), 0.0)))
                for (s, h), v in sorted(plan["closing"].items())]
        hs = pd.DataFrame(rows, columns=["SKU", "Hub", "Closing stock (kL)",
                                         "Safety-stock target (kL)",
                                         "Surplus/(shortfall) (kL)"])
        hs.to_excel(xw, sheet_name="Hub Stock Position", index=False)
        xw.sheets["Hub Stock Position"].set_column(0, 4, 20)

        # ---- 6/7. Norms -----------------------------------------------------------
        ncols = ["Product Name", "CFA", "Tier", "fill_rate_target",
                 "mu_day_kl", "sigma_day_kl", "fcst_bias_month_kl",
                 "LT_days", "sigma_LT_days", "z", "z_method",
                 "safety_stock_kl", "reorder_point_kl", "days_of_cover",
                 "ss_end_to_end_alt_kl", "flag"]
        norms[ncols].to_excel(xw, sheet_name="Norms - CFA", index=False)
        xw.sheets["Norms - CFA"].set_column(0, 12, 15)
        hub_norms.to_excel(xw, sheet_name="Norms - Hub", index=False)
        xw.sheets["Norms - Hub"].set_column(0, 10, 15)

        # ---- 8. Exceptions -----------------------------------------------------------
        ex = []
        for (s, cfa), q in sorted(plan["unmet"].items(), key=lambda kv: -kv[1]):
            ex.append(("UNMET DEMAND", s, cfa, q,
                       f"Lost sales; penalty {pen[s]:,.0f}/kL"
                       + ("; CONTRACTUAL" if contr[s] else "")))
        for (s, cfa), q in sorted(plan["buf_cfa"].items(), key=lambda kv: -kv[1]):
            ex.append(("CFA SS TOP-UP SHORT", s, cfa, q,
                       "CFA ends month below safety-stock norm"))
        for (s, h), q in sorted(plan["buf_hub"].items(), key=lambda kv: -kv[1]):
            ex.append(("HUB SS SHORT", s, h, q,
                       "Hub ends month below safety-stock target"))
        for _, r in norms[norms["flag"] != ""].iterrows():
            ex.append(("DATA FLAG", r["Product Name"], r["CFA"], np.nan, r["flag"]))
        exdf = pd.DataFrame(ex, columns=["Type", "SKU", "Location", "kL", "Note"])
        exdf.to_excel(xw, sheet_name="Exceptions", index=False)
        ws = xw.sheets["Exceptions"]
        ws.set_column(0, 0, 22); ws.set_column(1, 2, 16)
        ws.set_column(3, 3, 10); ws.set_column(4, 4, 70)
    return path
